### PR TITLE
add SM MC samples

### PR DESCRIPTION
**Pull request by Hooooon12**
added SM MC sample info files

### CODE REVIEW

**Comment by sihyunjeon** [comment]
Why only 2016 and 2017? 2018 doesn't exist?

**Comment by sihyunjeon** [comment]
Ah no sorry my email wasn't showing the full list

**Comment by helee** [comment]
I think we need to synchronize some sample names and remove the duplication.

For example, WZTo3LNu_amcatnlo -> WZTo3LNu, ZGTo2LG -> ZGToLLG

**Comment by jbhyun** [comment]
> I think we need to synchronize some sample names and remove the duplication.
> 
> For example, WZTo3LNu_amcatnlo -> WZTo3LNu, ZGTo2LG -> ZGToLLG

I agree with the idea that the samples with the same process needs to be named in the same way. But your comment doesn't seem to be proper examples. For WZTo3LNu, we have both powheg and amcatnlo sample, therefore they need to be distinguished with the suffix as "_amcatnlo". And all ZG->llg samples in the commits have consistently labeled with ZGTo2LG.

**Comment by sansan9401** [comment]
- We have used both names for ZGTo2LG: [2016 pre-Legacy](https://github.com/CMSSNU/SKFlatAnalyzer/blob/master/data/Run2Legacy_v4/2016/Sample/SampleSummary_MC.txt#L88), [2018 pre-Legacy](https://github.com/CMSSNU/SKFlatAnalyzer/blob/master/data/Run2Legacy_v4/2018/Sample/SampleSummary_MC.txt#L99). I think ZGToLLG is better to be consistent with the PD name. But as I will not use this sample, it should be decided by other people.
- *data/Run2UltraLegacy_v2/2016postVFP/Sample/ForSNU/ZGTo2LG.txt* and *data/Run2UltraLegacy_v2/2016postVFP/Sample/ForSNU/ZGTo2LG_01J.txt* have same content.
- And as I generated new GamGamToLL sample, the path has been changed. And the number of events is also a little bit different from previous one. I hope that all know that it is not a official sample. If you are not going to use this GamGamToLL sample, you can just remove the files related to this sample.

**Comment by sihyunjeon** [comment]
Maybe we can just come up with consistent naming strategies for UL? Discuss in the meeting?

**Comment by Hooooon12** [comment]
1. I will remove data/Run2UltraLegacy_v2/2016postVFP/Sample/ForSNU/ZGTo2LG.txt . This must be a typo.
2. ZGTo2LG --> ZGToLLG to be consistent with PD name.
3. I received new GamGamToLL sample info from HS and will update it.
4. Please note that GamGamToLL, WZJJ, WGJJ are private (not official).
5. https://docs.google.com/spreadsheets/d/1f2XMp0lvnlIZee9673OT3Yeibd3s_Jso4dlgFMT5dHY/edit#gid=1740432352
FYI, This is the full PD name that John actually called from DAS.

**Comment by Hooooon12** [comment]
No. I will add "private" to their PD name.

**Pull request merged**
