### PR TITLE
Add skims, MC and xsec

### PR DESCRIPTION
**Pull request by helee**
Add MC samples for Run2 analysis including DYJets and QCD in 2018.
Add SkimTree_Dilepton, SkimTree_HNFake.
Update xsec for MC samples, but some xsec values are not same for 3 years.
Samples with yellow color in the following google docs have issues and should be fixed.
https://docs.google.com/spreadsheets/d/1J4hn5YdbZr_0CgLT_lWz-Z-Pz3CM_3IkNtQzTVPMNrQ/edit?usp=sharing

### CODE REVIEW

**Comment by jedori0228** [comment]
I'll only comment on SingleTop;

I found this hypernews thread : https://hypernews.cern.ch/HyperNews/CMS/get/generators/4503/1/1.html

SIngleTop_sch_Lep : let's use the twiki value, 3.36
SingleTop_tW_antitop_NoFullyHad and SingleTop_tW_top_NoFullyHad : let's use 19.2
SingleTop_tch_antitop_Incl and SingleTop_tch_top_Incl : https://twiki.cern.ch/twiki/bin/view/LHCPhysics/SingleTopRefXsec#Single_top_t_channel_cross_secti we can take the values from this twiki; 


top | 136.02
anti-top | 80.95

**Comment by sansan9401** [comment]
Looks OK for me. But, could you resolve the conflict in Analyzers/include/Analyzers_LinkDef.h?

**Comment by helee** [comment]
Updates are finished from me.
For now we use 2016 xsec values for VV exlusive samples.

**Comment by sansan9401** [comment]
one comment on dy mass binned sample.
cross section for m3000toInf is not real. I couldn't find a confirmed value in xsec db, so I just used an abitrary small value.

________________________________

**Pull request merged**
