### PR TITLE
Update v3 2017 2018

### PR DESCRIPTION
**Pull request by sansan9401**
* Change sample name ZGTo2LG_01J -> ZGToLLG
* Adding 2017 and 2018 samples
* Still there are some missing files due to crab issue. You can check which sample is incomplete by using *checkMissingFiles.py* script.
```
[hsseo@tamsa1 SKFlatAnalyzer_UL]$ python python/checkMissingFiles.py
2016postVFP MuonEG_G : 432 / 434
2016postVFP QCD_Pt_800to1000 : 420 / 421
2016postVFP QCD_Pt_1000to1400 : 224 / 225
2016postVFP QCD_Pt_1800to2400 : 62 / 63
2016preVFP DYJets : 506 / 508
2016preVFP DYJets_Pt-650ToInf : 35 / 36
2016preVFP QCD_bEnriched_HT100to200 : 140 / 141
2017 MuonEG_C : 514 / 518
2017 SingleMuon_B : 263 / 264
2017 SingleMuon_C : 540 / 541
2017 QCD_bEnriched_HT100to200 : 245 / 246
2017 QCD_bEnriched_HT700to1000 : 26 / 27
2017 SingleTop_tch_top_Incl : 819 / 820
2017 TTLJ_powheg : 2177 / 2178
2018 EGamma_A : 558 / 565
2018 SingleMuon_B : 271 / 272
2018 SingleMuon_D : 1260 / 1264
2018 DYJets_Pt-50To100 : 1131 / 1133
2018 QCD_Pt_30to50 : 121 / 122
2018 QCD_Pt_300to470 : 622 / 624
2018 QCD_Pt_470to600 : 566 / 568
2018 TTLL_powheg : 1549 / 1550
2018 ttZToQQ_ll : 122 / 123
```

### CODE REVIEW

**Comment by sihyunjeon** [comment]
+1

**Comment by sihyunjeon** [comment]
For the missing samples (for data especially), can we just scp them and run them locally?

**Comment by sansan9401** [comment]
I found that copying from disk also not work, but I can try with the tape.

**Comment by sihyunjeon** [comment]
tape won't be accessible uhmmm

**Pull request merged**
