### PR TITLE
typo corrected

### PR DESCRIPTION
**Pull request by sihyunjeon**

### CODE REVIEW

**Comment by jalmond** [comment]
Why do you delete the linkdef file?

**Comment by sihyunjeon** [comment]
@jalmond I made a mistake on that. So I made a pull request again, LinkDef is still not there?

**Comment by jedori0228** [comment]
it was added somehow later so I merged it

**Comment by sihyunjeon** [comment]
@jedori0228 @jalmond Yes I added later and did pull request again, thanks.

**Pull request merged**
