### PR TITLE
Update Type1 samples and QCD Lep enricjed samples

### PR DESCRIPTION
**Pull request by jalmond**
I added code I use for making sample lists from google doc. This is in SKFlatSampleList/ and does not effect others so Its simply there if people wish to use it.

### CODE REVIEW

**Comment by sihyunjeon** [comment]
Can we move skflatsamplelist under script directory?

**Comment by jalmond** [comment]
I can move skflatsamplelist to scripts yeah. I will wait for @sansan9401 comments on how to terat signal samples in the Sample/ directories

**Comment by sansan9401** [comment]
I think it should be discussed with other users as well. Personally, I prefer to keep only SM samples at common branch. If users have some difficulty to manage sample list, we may consider to change structure a bit.

**Comment by sihyunjeon** [comment]
can you bring this up in tmrw's meeting?
but if typei people has additional lines in summary.txt file for the signals,
and later if somebody adds SM bkg sample to the summary.txt file,
when typei people try to merge from the master branch,
would there be any conflicts? john and i are concerned about this

**Comment by sansan9401** [comment]
As I know, summary text file is just for summary, not used by SKFlat.py. In past, I remember that there was a separated summary txt file for signal samples in users' repository (something like SampleSummary_PrivateMC.txt?).

**Comment by jbhyun** [comment]
I also prefer to keep the tradition: SM samples to be in the master branch, but signal sample lists should not be merged to master branch.

btw. Sihyun, adding a few lines to the summary.txt by mistake from anybody would not matter much.
It is not used in any of the default code. The information of cross sections, sum weights, and paths are taken from ForSNU/ and CommonSampleInfo/.
And even if anybody added some unnecessary lines in summary.txt, running Summarize.py will fix it automatically from the list of text files in ForSNU, as long as signal samples are not added to the ForSNU directory in master branch



________________________________

**Comment by jbhyun** [comment]
yes, we can add some exception lines in the Summarize.py if we don't want to include signal samples. Jaesung and Sungbin's examples are still in the code.

________________________________

**Comment by sihyunjeon** [comment]
> And even if anybody added some unnecessary lines in summary.txt, running Summarize.py will fix it automatically from the list of text files in ForSNU, as long as signal samples are not added to the ForSNU directory in master branch

I mean when I have 900 lines in summary.txt that's not submitted to the branch,
and if somebody adds some SM sample in summary.txt
and then if I try to merge my branch with other updates this might cause merge conflict every time for me, no?
This is a bit annoying because `UpdateCommonSampleInfo.sh` always updates the txt file.

**Comment by jbhyun** [comment]
I didn't know you were using that shell script. I've never used it.
I merely tried to say there will be no functional difference or problem in the analysis from whatever the changes made in the text files. No offense :)
If fixing merge conflicts on those files matters to you, as I said in the second thread, I don't really have objection on making some changes.

________________________________

**Pull request closed without merging**
