### PR TITLE
tool for top pt reweight in MCCorrection

### PR DESCRIPTION
**Pull request by bhoh**
I think it is useful for those who use TTbar sample.

ref: https://twiki.cern.ch/twiki/bin/viewauth/CMS/TopPtReweighting2017

### CODE REVIEW

**Comment by jedori0228** [comment]
Hi @bhoh , everything looks good to me, but I wonder if those values are also okay for 2016, or 2017 only?

**Comment by bhoh** [comment]
@jedori0228 This is the latest top-pt-reweighting function estimated using 2015 data.
But, It is applicable to Run2 TTbar(Powheg+Pythia8, default set up used in Run2) samples.

**Comment by sungbinoh** [comment]
Looks fine for be too.

**Comment by jedori0228** [comment]
> @jedori0228 This is the latest top-pt-reweighting function estimated using 2015 data.
> But, It is applicable to Run2 TTbar(Powheg+Pythia8, default set up used in Run2) samples.

Thanks! I merge it now.

**Pull request merged**
